url: rotonitkweb.github.io
baseurl: /

# Site settings
title: Rotaract Club NITK Chapter
email: rotonitk@gmail.com
description: Official website for the Rotaract Club NITK Chapter.

# Team names, titles and social links
people:
- name: Rtr.Joel Chacko 
  pic: 1.png
  position: Director Club services
  social:
    - title: google
      url: joelcjacob99@gmail.com
    - title: facebook
      url: https://www.facebook.com/joel.chacko.99
    - title: linkedin
      url: https://www.linkedin.com/in/joelchackojacob/

- name: Rtr. Vineetha Sunny  
  pic: 2.png
  position: President
  social:
    - title: google
      url: vineethasunny108@outlook.com
    - title: facebook
      url: https://www.facebook.com/vhearts.sunny
    - title: linkedin
      url: https://www.linkedin.com/in/vineetha-sunny-7240241b2/

- name: Rtr. Annlin Chacko 
  pic: 3.png
  position: Secretary
  social:
    - title: google
      url: annlinchacko@gmail.com
    - title: facebook
      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/annlin-chacko-52a0b2193/

- name: Rtr. Sharon Tony
  pic: 4.png
  position: Joint Convenor
  social:
    - title: google
      url: sharonmaenam@gmail.com
    - title: facebook
      url: https://www.facebook.com/sharontony.maenam.9
    - title: linkedin
      url: https://www.linkedin.com/in/sharon-tony-maenam-7a1744199/

- name: Rtr. Derek Joel
  pic: 5.png
  position: Vice President
  social:
    - title: google
      url: derekjoelgeorge@outlook.com
    - title: facebook
      url: https://www.facebook.com/derek.joel.355
    - title: linkedin
      url: https://www.linkedin.com/in/derek-joel-555392176/

- name: Rtr. Sathwik Kanneganti
  pic: 6.png
  position: Joint Secretary
  social:
    - title: google
      url: sathwikkanneganti19@gmail.com
    - title: facebook
      url: https://www.facebook.com/sathwik.kanneganti
    - title: linkedin
      url: https://www.linkedin.com/in/sathwikkanneganti/

- name: Rtr. Tejas Chenoth
  pic: 7.png
  position: Sergeant at Arms
  social:
    - title: google
      url: tejasmahe@gmail.com
    - title: facebook
      url: https://www.facebook.com/tejas.chenoth
    - title: linkedin
      url: https://www.linkedin.com/in/tejas-chenoth-866382176/

- name: Rtr. Anamika Karthy
  pic: 8.jpg
  position: Director Vocational Services
  social:
    - title: google
      url: anamikathachanattil@gmail.com
    - title: facebook
      url: https://www.facebook.com/anamika.karthy.7
    - title: linkedin
      url: https://www.linkedin.com/in/anamika-karthy-2084961a6/

- name: Rtr. Chaitra Satheesh
  pic: 9.png
  position: Director Community Services
  social:
    - title: google
      url: s.chaitra12@gmail.com
    - title: facebook
      url: https://www.facebook.com/chaitra.s03
    - title: linkedin
      url: https://www.linkedin.com/in/chaitra-satheesh-1b7243195/

- name: Rtr. Ananthu M Nair
  pic: 10.png
  position: Chairman Public Relations
  social:
    - title: google
      url: ananthu192@gmail.com
    - title: facebook
      url: https://www.facebook.com/ananthu.192
    - title: linkedin
      url: https://www.linkedin.com/in/ananthu-nair-a70193182/

- name: Rtr. Sudarshan Sundar
  pic: 11.png
  position: Chairman Alumni 
  social:
    - title: google
      url: sudarshan99sundar@gmail.com
    - title: facebook
      url: https://www.facebook.com/sudarshan99sundar
    - title: linkedin
      url: https://www.linkedin.com/in/sudarshan-sundar-68a93a194/

- name: Rtr. Nihal Haneef
  pic: 12.png
  position: Chairman Technical
  social:
    - title: google
      url: nihalh55@gmail.com
    - title: facebook
      url: https://www.facebook.com/Nihal.af98
    - title: linkedin
      url: https://www.linkedin.com/in/nihalhaneef/

- name: Rtr. Gayatri Sajeev
  pic: 13.png
  position: Director International Affairs
  social:
    - title: google
      url: gayatrisajeev1@gmail.com
    - title: facebook
      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/gayatri-sajeev-4538a7174/

- name: Rtr. Vineetha Wilson
  pic: 14.png
  position: Chairwoman Cultural 
  social:
    - title: google
      url: vineetha.wilson9809@gmail.com
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Rtr. Liz George
  pic: 15.png
  position: Treasurer
  social:
    - title: google
      url: lizgeorge00@hotmail.com
    - title: facebook
      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/liz-george-663a1719b/

legal: "Privacy Policy"
social:
  - url: https://www.facebook.com/RotaractClubNITK/
    icon: "fa fa-facebook"
  - url: https://www.linkedin.com/company/rotaract-club-nitk-chapter/
    icon: "fa fa-linkedin"
  - url: https://www.youtube.com/channel/UChDkd089CGeiYpAySOdcE0A
    icon: "fa fa-youtube"
  - url: https://www.instagram.com/rotaract_nitk/
    icon: "fa fa-instagram"

analytics:
  google:

# Postal address (add as many lines as necessary)
address:
  - line: NITK Surathkal
  - line: P.O Srinivasnagar, Karnataka, India 575025

# Build settings
markdown: kramdown
permalink: pretty
